import React, { useState, useEffect } from 'react';
import { TrendingUp, TrendingDown, RefreshCw, Trophy, Bitcoin, AlertCircle } from 'lucide-react';

const PortfolioTracker = () => {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [lastUpdate, setLastUpdate] = useState(null);
  const [priceData, setPriceData] = useState({});

  // Fetch from the JSON file generated by Python script
  const DATA_URL = './portfolio_data.json';
  
  const portfolios = [
    { name: 'Heather', canada: 'PPL', us: 'NVDA', intl: 'DNNGY' },
    { name: 'Mason', canada: 'SHOP', us: 'NVDA', intl: 'DNNGY' },
    { name: 'Michael', canada: 'CSU', us: 'UNH', intl: 'ASML' },
    { name: 'Mark', canada: 'TOU', us: 'MSFT', intl: 'TSM' },
    { name: 'Beau', canada: 'AIF', us: 'BDX', intl: 'LVMUY' },
    { name: 'Marcus', canada: 'OTEX', us: 'UNH', intl: 'BAESY' },
    { name: 'Jestine', canada: 'CAE', us: 'ORCL', intl: 'SE' }
  ];

  const fetchLivePrices = async () => {
    setLoading(true);
    setError(null);
    
    try {
      const response = await fetch(DATA_URL + '?t=' + Date.now()); // Cache busting
      
      if (!response.ok) {
        throw new Error(`Failed to fetch data: ${response.statusText}`);
      }
      
      const data = await response.json();
      setPriceData(data);
      setLastUpdate(new Date(data.last_updated));
      setError(null);
    } catch (err) {
      console.error('Error fetching prices:', err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLivePrices();
    const interval = setInterval(fetchLivePrices, 300000); // Refresh every 5 minutes
    return () => clearInterval(interval);
  }, []);

  const calculateReturn = (ticker) => {
    const stock = priceData.stocks?.[ticker];
    if (!stock) return 0;
    
    const priceReturn = (stock.current_price / stock.baseline_price) - 1;
    const dividendReturn = stock.dividends_since_baseline / stock.baseline_price;
    return priceReturn + dividendReturn;
  };

  const calculatePortfolioReturn = (portfolio) => {
    const canadaReturn = calculateReturn(portfolio.canada);
    const usReturn = calculateReturn(portfolio.us);
    const intlReturn = calculateReturn(portfolio.intl);
    return (canadaReturn + usReturn + intlReturn) / 3;
  };

  const sortedPortfolios = [...portfolios].sort((a, b) => {
    const returnA = calculatePortfolioReturn(a);
    const returnB = calculatePortfolioReturn(b);
    return returnB - returnA;
  });

  const bitcoinReturn = priceData.bitcoin?.current_price 
    ? (priceData.bitcoin.current_price / priceData.bitcoin.baseline_price) - 1 
    : 0;
  const bitcoinValue = 700 * (1 + bitcoinReturn);

  const formatPercent = (value) => {
    return `${value >= 0 ? '+' : ''}${(value * 100).toFixed(2)}%`;
  };

  const formatCurrency = (value) => {
    return new Intl.NumberFormat('en-CA', {
      style: 'currency',
      currency: 'CAD',
      minimumFractionDigits: 2
    }).format(value);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950">
      <div className="fixed inset-0 opacity-10">
        <div className="absolute inset-0" style={{
          backgroundImage: `linear-gradient(rgba(59, 130, 246, 0.1) 1px, transparent 1px),
                           linear-gradient(90deg, rgba(59, 130, 246, 0.1) 1px, transparent 1px)`,
          backgroundSize: '50px 50px'
        }} />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 py-8">
        <div className="mb-12">
          <div className="flex items-center justify-between mb-6 flex-wrap gap-4">
            <div>
              <h1 className="text-5xl font-bold bg-gradient-to-r from-blue-400 via-cyan-400 to-teal-400 bg-clip-text text-transparent mb-2">
                Portfolio Competition
              </h1>
              <p className="text-slate-400 text-lg">
                Live tracking since September 19, 2024
              </p>
            </div>
            <button
              onClick={fetchLivePrices}
              disabled={loading}
              className="flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-blue-600/30"
            >
              <RefreshCw className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
              {loading ? 'Updating...' : 'Refresh Prices'}
            </button>
          </div>
          
          {lastUpdate && !error && (
            <div className="text-slate-500 text-sm">
              Last updated: {lastUpdate.toLocaleString('en-CA', {
                month: 'short',
                day: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
              })}
            </div>
          )}

          {error && (
            <div className="mt-4 p-4 bg-red-500/10 border border-red-500/20 rounded-lg flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
              <div>
                <div className="text-red-400 font-semibold">Error loading data</div>
                <div className="text-red-300/80 text-sm mt-1">{error}</div>
                <div className="text-slate-400 text-xs mt-2">
                  Make sure portfolio_data.json exists and is accessible.
                </div>
              </div>
            </div>
          )}
        </div>

        {!error && priceData.bitcoin && (
          <>
            <div className="mb-8 p-6 bg-gradient-to-br from-orange-500/10 to-yellow-500/10 border border-orange-500/20 rounded-xl backdrop-blur-sm">
              <div className="flex items-center justify-between flex-wrap gap-4">
                <div className="flex items-center gap-3">
                  <Bitcoin className="w-8 h-8 text-orange-400" />
                  <div>
                    <h3 className="text-xl font-bold text-orange-400">Bitcoin Prize Pool</h3>
                    <p className="text-slate-400 text-sm">$700 CAD invested on Sep 19</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-3xl font-bold text-white">
                    {formatCurrency(bitcoinValue)}
                  </div>
                  <div className={`text-lg font-semibold ${bitcoinReturn >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                    {formatPercent(bitcoinReturn)}
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-slate-900/50 backdrop-blur-sm rounded-2xl border border-slate-800 overflow-hidden shadow-2xl">
              <div className="p-6 border-b border-slate-800 bg-gradient-to-r from-slate-800 to-slate-900">
                <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                  <Trophy className="w-6 h-6 text-yellow-400" />
                  Leaderboard
                </h2>
              </div>
              
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-slate-800">
                      <th className="px-6 py-4 text-left text-sm font-semibold text-slate-400 uppercase tracking-wider">Rank</th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-slate-400 uppercase tracking-wider">Student</th>
                      <th className="px-6 py-4 text-center text-sm font-semibold text-slate-400 uppercase tracking-wider">Canada</th>
                      <th className="px-6 py-4 text-center text-sm font-semibold text-slate-400 uppercase tracking-wider">U.S.</th>
                      <th className="px-6 py-4 text-center text-sm font-semibold text-slate-400 uppercase tracking-wider">International</th>
                      <th className="px-6 py-4 text-right text-sm font-semibold text-slate-400 uppercase tracking-wider">Return</th>
                      <th className="px-6 py-4 text-right text-sm font-semibold text-slate-400 uppercase tracking-wider">Portfolio Value</th>
                    </tr>
                  </thead>
                  <tbody>
                    {sortedPortfolios.map((portfolio, index) => {
                      const portfolioReturn = calculatePortfolioReturn(portfolio);
                      const portfolioValue = 10000 * (1 + portfolioReturn);
                      const isLeader = index === 0;
                      
                      return (
                        <tr
                          key={portfolio.name}
                          className={`border-b border-slate-800 hover:bg-slate-800/30 transition-colors ${
                            isLeader ? 'bg-gradient-to-r from-yellow-500/5 to-transparent' : ''
                          }`}
                        >
                          <td className="px-6 py-4">
                            <div className={`flex items-center justify-center w-8 h-8 rounded-full font-bold ${
                              isLeader 
                                ? 'bg-gradient-to-br from-yellow-400 to-orange-500 text-slate-900'
                                : index === 1
                                  ? 'bg-gradient-to-br from-slate-400 to-slate-500 text-slate-900'
                                  : index === 2
                                    ? 'bg-gradient-to-br from-amber-600 to-amber-700 text-white'
                                    : 'bg-slate-800 text-slate-400'
                            }`}>
                              {index + 1}
                            </div>
                          </td>
                          <td className="px-6 py-4">
                            <div className="font-semibold text-white flex items-center gap-2">
                              {portfolio.name}
                              {isLeader && <Trophy className="w-4 h-4 text-yellow-400" />}
                            </div>
                          </td>
                          <td className="px-6 py-4">
                            <StockCell ticker={portfolio.canada} data={priceData.stocks?.[portfolio.canada]} />
                          </td>
                          <td className="px-6 py-4">
                            <StockCell ticker={portfolio.us} data={priceData.stocks?.[portfolio.us]} />
                          </td>
                          <td className="px-6 py-4">
                            <StockCell ticker={portfolio.intl} data={priceData.stocks?.[portfolio.intl]} />
                          </td>
                          <td className="px-6 py-4 text-right">
                            <div className={`flex items-center justify-end gap-2 font-bold text-lg ${
                              portfolioReturn >= 0 ? 'text-green-400' : 'text-red-400'
                            }`}>
                              {portfolioReturn >= 0 ? <TrendingUp className="w-5 h-5" /> : <TrendingDown className="w-5 h-5" />}
                              {formatPercent(portfolioReturn)}
                            </div>
                          </td>
                          <td className="px-6 py-4 text-right">
                            <div className="font-semibold text-white text-lg">
                              {formatCurrency(portfolioValue)}
                            </div>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="mt-8 text-center text-slate-500 text-sm">
              <p>Equal-weighted portfolios starting at $10,000 CAD • Returns include dividends</p>
              <p className="mt-2">
                <span className="inline-block px-3 py-1 bg-green-500/10 border border-green-500/20 rounded-full text-green-400">
                  ✓ Live data from Yahoo Finance
                </span>
              </p>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

const StockCell = ({ ticker, data }) => {
  if (!data) {
    return (
      <div className="text-center">
        <div className="text-slate-400 text-sm font-mono">{ticker}</div>
        <div className="text-slate-600 text-xs">No data</div>
      </div>
    );
  }

  const returnPct = (data.current_price / data.baseline_price - 1) * 100;
  const totalReturn = returnPct + ((data.dividends_since_baseline / data.baseline_price) * 100);
  const isPositive = totalReturn >= 0;

  return (
    <div className="text-center">
      <div className="text-slate-300 text-sm font-mono font-semibold">{ticker}</div>
      <div className={`text-xs font-semibold ${isPositive ? 'text-green-400' : 'text-red-400'}`}>
        {isPositive ? '+' : ''}{totalReturn.toFixed(1)}%
      </div>
      <div className="text-slate-500 text-xs">${data.current_price.toFixed(2)}</div>
    </div>
  );
};

export default PortfolioTracker;
